### PR TITLE
PR 1

### PR DESCRIPTION
**Pull request by anonymous1184**
This is basically just a bit of clean up, formatting and a couple of  spelling issues. Unfortunately my settings trimmed the white space in the script, so if you don't want that I guess I can manually track the changes and redo without messing with the white space.

I stopped without finishing as I realized I was applying my criteria when redacting technical documentation and perhaps that is not something you're interested in.

Let me know if still interested.

### CODE REVIEW

**Comment by Gewerd-Strauss** [comment]
I don't particularly care about the trimmed white space, and was surprised about all the spelling errors I apparently made... Must have been sloppy myself :/ The only whitespace that'll have to be reversed are the long patches of whitespace in  [lines 21 and 22](https://github.com/anonymous1184/DistractLess/blob/dev/DistractLess.ahk#L21-L22), because they are required for my versioning script to function. I could rework that to work properly with a tf_function, but so far I didn't require to do so. 
That I can do by hand, obviously.. Every other whitespace can be removed for all I care. I generate new because the entire code is indented by one tab, and as a result every line has one tab worth of whitespace. It's a purely cosmetic thing, I just dislike having the text at the left side. Superficial, I know :P

---
>I stopped without finishing as I realized I was applying my criteria when redacting technical documentation and perhaps that is not something you're interested in.

I am not sure I know the extend of your criteria, but from what I've seen I'd be certainly interested - and eager to learn, btw :P 

---

I didn't even know GH had a format for hotkeys in its markdown flair, pretty sure that's not base markdown. Also, thanks to you I realised I've been misunderstanding and misusing "to redact" for maybe three years now.

(ノಠ益ಠ)ノ彡┻━┻ 

---

Additionally, I'd like an outsider who is _not_ intimately aware of the source-code, but with understanding of the ahk lingo to check if the documentation is _sensible_, or if I have written something that is destined to confuse anyone but me. I can't check that, I know my own code too well to not autocorrect logical leaps unknowingly.  

I believe I managed to make most of the documentation very straight-forward. The hairy bits is [Understanding the filter](https://github.com/anonymous1184/DistractLess/tree/dev#5-understanding-the-filter), because it's somewhat difficult to put into words, and even the diagrams are not perfect. The question I am asking you is "If you were to read the documentation from the perspective of a user, does this chapter manage to convey how the mechanism works?". Because that's the **one singular** thing the user must know to _not_ make themselves very unhappy by suddenly closing stuff they desperately can't have closed.

I acknowledge that you might also be "overqualified\*" in your definitively exceeding level of knowledge regarding ahk and lingo pitfalls, but you're probably the only one I'd be okay with asking right now. 

The big problem is that once this is out, I can't assume the level of knowledge people bring to the table. But I suppose this is  true for any kind of documentation - do you write for informed people, experts or the general public; the answer widely influences the lens through which one needs to phrase text. Not to mention preconceptions regarding language varies from culture to culture and within themselves. Technical docs are good because certain phrases are _defined_ to have a specific meaning, but a "common" person might/will have a  hard time anyways. 

---

Learned that the hard way during my studies when I was suddenly reading A-grade high-impact papers on biotechnological topics. Yeah sure, I study that shit and know my way around vaguely, but consuming expert-grade texts is fucking exhausting if you're not an expert. 

---
\* or rather too smart

**Comment by anonymous1184** [comment]
> I am not sure I know the extend of your criteria, but from what I've seen I'd be certainly interested

I've been in charge of people coding for some years now, I also been professionally programming since 2000. We can go trough that on a chat.

> format for hotkeys in its markdown flair, pretty sure that's not base markdown

Well markdown can be mixed with html, I used the `<kbd>` tag.

---

As for what I write, is always technical because is for other programmers to consume. I refrained from read the source code as I wanted to focus on the README and not fall into the same as you: leave something out because I know how it works.

And yes, is quite complex the filter... to be honest I still haven't figured out myself (I remember not being able from the post on Reddit).

So, accept the pull or cherry pick whatever you like and we can go from there.

As for overqualified, thanks for the compliment but I'm just hanging around here and there :P

**Comment by Gewerd-Strauss** [comment]
So trying to put the filter mechanism into a couple diagrams failed to convey it somewhat clearly? 

Hmm, that's bad, but not exactly unexpected. I'll see if I can figure out a way to do it better then, I suppose. 

Any part in particular that's a hassle to grasp, or just a general failure?

**Comment by anonymous1184** [comment]
Sorry I missed this, it's been kinda crazy for me :P

> So trying to put the filter mechanism into a couple diagrams failed to convey it somewhat clearly?

I don't think that you would be the issue. Since ever I'm the kind of person that ditches everything that is "not easy", I'm a big fan of simplicity and plain things... that said most likely is my fault as my brain only figures out:

- White list
- Black list
- Exceptions

Certainly not a failure on your end, but on mine because I've been reading the document and still I cannot figure out how I'm gonna be able to tell which mode I'm in and which of the rules the app will follow if I have white, black, both for a match and how is gonna work when I have multiple. Plus I don't know how I'm I gonna remember where do I stand without reading the rules and mentally process them.

I guess this comes from a previous time where I used software Firewall and rules were either/or with exceptions, and pretty much any app that works with lists works the same; so having not just the two lists active at the same time but also a _both_ mode cracks my simpleton brain.

---

I'm gonna give the formatting and spelling another go (this time the project has a don't mess with white-space preference enabled).

**Pull request merged**
